### ISSUE TITLE
How to add rule for cucumber annotations Given, When and Then

### ISSUE THREAD

**Issue by Rishikantpd** [darrinholst/eslint-plugin-cucumber#13]
Eslint identifies Given When Then as new-cap error 
How to set rules for eslint so that it can ignore Given when and Then

**Comment by sladg** [comment]
Any news? Looking into this as well.

**Comment by darrinholst** [comment]
That rule is a part of eslint, not this plugin. You have options for configuring it [here](https://eslint.org/docs/latest/rules/new-cap#options)
