### ISSUE TITLE
Support for other adverbs in async-then, and for hooks generally

### ISSUE THREAD

**Issue by davidjgoss** [darrinholst/eslint-plugin-cucumber#6]
The `async-then` rule, as the name implies, only checks that usages of `Then` work asynchronously. However in the project I work on and others I've seen, our `Given`s and `When`s all use async stuff too, as do the `Before` and `After` hooks.

It would be good to legislate for this with the same rule. What was the reasoning for targeting `Then` with this rule originally? I was going to look at running up a pull request to support the others, but feel I am probably missing something about the original intent...

**Comment by darrinholst** [comment]
@davidjgoss Thanks for the interest and work on this. The projects I was working on at the time didn't always have async givens and whens so I didn't want to enforce it on those. Also it was pre async/await (at least as the norm) so it wasn't as easy as just adding the async keyword for those steps that weren't async. I'd suggest adding the option to check other verbs as the no-restricted-tags does.

**Comment by davidjgoss** [comment]
Makes sense, will do that, thanks!

**Comment by davidjgoss** [comment]
Fixed via that PR that was merged manually
